import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('kc-house-data.csv')

plt.figure(figsize = (10, 6))
plt.hist(data['price'], bins=30, edgecolor = 'black')
plt.title('Распределение цен на недвижимость')
plt.xlabel('Цена (USD)')
plt.ylabel('Количество домов')
plt.grid(True)
plt.show()

plt.figure(figsize = (10, 6))
plt.hist(data['sqft_living'], bins=30, edgecolor = 'black')
plt.title('Распределение жилой площади')
plt.xlabel('Жилая площадь (sqft)')
plt.ylabel('Количество домов')
plt.grid(True)
plt.show()

plt.figure(figsize = (10, 6))
plt.hist(data['yr_built'], bins=30, edgecolor = 'black')
plt.title('Распределение года постройки')
plt.xlabel('Год постройки')
plt.ylabel('Количество домов')
plt.grid(True)
plt.show()

plt.figure(figsize = (10, 6))
data['waterfront'].value_counts().plot(kind='bar', color=['skyblue','salmon'])
plt.title('Распределение домов по наличию вида на набережную')
plt.xlabel('Вид на набережную')
plt.ylabel('Количество домов')
plt.xticks([0, 1], ['Нет', 'Да'], rotation=0)
plt.grid(axis='y')
plt.show()

plt.figure(figsize = (10, 6))
data['floors'].value_counts().plot(kind='bar', color=['skyblue','salmon'])
plt.title('Распределение домов по количеству этажей')
plt.xlabel('Количество этажей')
plt.ylabel('Количество домов')
plt.grid(axis='y')
plt.show()

plt.figure(figsize = (10, 6))
data['condition'].value_counts().plot(kind='bar', color=['skyblue','salmon'])
plt.title('Распределение состояния домов')
plt.xlabel('Состояние домов')
plt.ylabel('Количество домов')
plt.grid(axis='y')
plt.show()

plt.figure(figsize=(12, 6))
plt.scatter(data['bedrooms'], data['price'], alpha=0.5,
color='blue')
plt.title('Цена недвижимости в зависимости от количества спален')
plt.xlabel('Количество спален')
plt.ylabel('Цена (USD)')
plt.grid(True)
plt.show()

plt.figure(figsize=(12, 6))
plt.boxplot([data[data['condition'] == i]['price'] for i in sorted(data['condition'].unique())], labels=sorted(data['condition'].unique()))
plt.title('Цена недвижимости в зависимости от состояния')
plt.xlabel('Состояние дома')
plt.ylabel('Цена (USD)')
plt.grid(True)
plt.show()

plt.figure(figsize=(12, 6))
plt.boxplot([data[data['floors'] == i]['price'] for i in sorted(data['floors'].unique())], labels=sorted(data['floors'].unique()))
plt.title('Цена недвижимости в зависимости от этажности')
plt.xlabel('Количество этажей')
plt.ylabel('Цена (USD)')
plt.grid(True)
plt.show()

plt.figure(figsize=(12, 6))
data.boxplot(column='price', by='waterfront', grid=False)
plt.title('Цена недвижимости в зависимости от наличия вида на набережную')
plt.suptitle('')
plt.xlabel('Вид на набережную')
plt.ylabel('Цена (USD)')
plt.xticks([1, 2], ['Нет', 'Да'])
plt.grid(True)
plt.show()

plt.figure(figsize=(12, 6))
plt.scatter(data['sqft_living'], data['price'], alpha=0.5, color='green')
plt.title('Цена недвижимости в зависимости от площади жилой зоны')
plt.xlabel('Жилая площадь (sqft)')
plt.ylabel('Цена (USD)')
plt.grid(True)
plt.show()
